source 'https://rubygems.org'
gem 'bundler'
gem 'sinatra'
gem 'twitter', '~> 6.2'
gem 'json'
gem 'omniauth-twitter'
gem 'sinatra-flash'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'minitest'
gem 'rake'
gem 'cucumber'
gem 'capybara'
gem 'rspec'
gem 'simplecov'
gem 'sprockets'
gem 'uglifier'
gem 'sass'
gem 'sinatra-contrib'
group :development, :test do
  gem 'sqlite3'
end
gem 'bcrypt' 