source 'https://rubygems.org'
gem 'sinatra'
gem 'thin'
gem 'twitter', '~> 6.2'
gem 'sqlite3'
gem 'json'
gem 'omniauth-twitter'
gem 'sinatra-flash'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'cucumber'
gem 'capybara'
gem 'rspec'
gem 'simplecov'