source 'https://rubygems.org'
gem 'bundler'
gem 'sinatra'
gem 'twitter', '~> 6.2'
gem 'json'
gem 'omniauth-twitter'
gem 'sinatra-flash'
gem 'activerecord', '~> 5.2.0'
gem 'sinatra-activerecord'
gem 'minitest'
gem 'rake'
gem 'cucumber'
gem 'capybara'
gem 'rspec'
gem 'simplecov'
gem 'sprockets'
gem 'uglifier'
gem 'sass'
gem 'sinatra-contrib'
group :development, :test do
  gem 'sqlite3'
end
group :production do
  gem 'pg'
end
gem 'bcrypt' 
gem 'pony'
gem 'prawn', '~> 1.2.1'
gem 'prawn-table', '~>0.1.0'
