production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  
development:
  adapter: sqlite3
  database: db/piepiper.db
  pool: 5
  timeout: 5000
  
test:
  adapter: sqlite3
  database: db/piepiper.db
  pool: 5
  timeout: 5000